inikulin/parse5

README.md
lib/tree_construction/location_info_mixin.js
test/fixtures/parser_test.js

The parser, as of now only provides location information for a complete block, and not for the individual tags.
In my case needed location for both, start and end tags separately. Some other people might as well need it.
These are the minimum changes that I felt were required to make that happen. The tag locations can be accessed using __startTagLocation and __endTagLocation respectively.
Kindly review
Thanks!

Enhanced location info

---

lib/parser/index.js
lib/serializer/index.js

Minor change. I think that a link to a wiki page/etc explaining just how and what non-conformities can occur would be helpful. I'm even wondering as you read this.

grammar fix in api docs

---

docs/05_api_reference.md
lib/location_info/parser_mixin.js
lib/location_info/tokenizer_mixin.js
lib/tokenizer/index.js
test/benchmark/bench-huge.js
test/benchmark/bench-micro.js
test/benchmark/bench-pages.js
test/benchmark/bench-stream.js
test/fixtures/location_info_parser_test.js

This is based on the work by @sakagg in #59 , with additional changes that:
- based off the latest 2.0 master;
- attrs location info attached to both `node.__location` and `node.__location.startTag`, as suggested in [this comment](https://github.com/inikulin/parse5/pull/59#issuecomment-130285405);
- fixed and ran the regression benchmark with the following result (no significant perf regression):

Location info for Attributes (2.0)

---

lib/location_info/tokenizer_mixin.js
test/fixtures/location_info_parser_test.js

In my PR for attribute location I forgot to also overwrite `tokenizer._leaveAttrName` - which causes missing location info for attributes with no value.
For example, `<div some-attr></div>` would have an `attrs` array of length 1, but no `__location.attrs`.

fix attribute location info for empty attributes

---

lib/location_info/tokenizer_mixin.js
lib/tokenizer/index.js

Since the related spec editorial changes have landed and we've seen no evidence of performance degradation in parse5 while it does simplify some code, decided to send those local commits as a PR.

Avoid some code duplication

---

lib/sax/index.js

Fix attribute form for SAXParser 'startTag'

---

lib/location_info/tokenizer_mixin.js
test/fixtures/location_info_parser_test.js

When consuming tokens in script tags, a `<` right before a newline would cause the line number calculation to be offset by 1. Repo case:
```html
<!DOCTYPE html>
<html>
<body>
<script>
var x = window.scrollY <
100; //line number is now off by one
</script>
</html>
```
Simply setting the `isEol` flag to false when unconsuming a token corrects the issue.

Fix line number calculation bug

---

lib/location_info/parser_mixin.js
test/fixtures/location_info_parser_test.js

3a3515a seems to have introduced an error for all other elements (non-implicitly closed elements), as can be seen in the included test.
Kinda weird that it wasn’t caught before!
Cheers

Fixed incorrect LocationInfo.endOffset for non-implicitly closed elements

---

test/data/parser_feedback/domjs-unsafe.test
test/data/parser_feedback/pending-spec-changes-plain-text-unsafe.test
test/data/parser_feedback/plain-text-unsafe.test
test/test_utils.js

Previously, this character was invisible in the test output.
Escaping as `\u0000` and not just `\0` for consistency with other tests.

Escape NUL character in feedback tests

---

lib/serializer/index.js

Small thing, but I noticed that there was a duplicated `tn !== $.BR` condition while going through the code.

Remove duplicate condition

---

scripts/generate-named-entity-data/index.js

Underscore should be a dash.
Affects the code and the comment that is written to the auto-generated file
(ran into the broken link while troubleshooting)

Fixing broken link to README.md file

---

packages/parse5/lib/common/error-codes.js
packages/parse5/lib/tokenizer/index.js

`missingWhitespaceBetweenDoctypePublicAndSytemIdentifier` >
`missingWhitespaceBetweenDoctypePublicAndSystemIdentifiers`
Closes GH-255.

Fix internal error name

---

packages/parse5-parser-stream/docs/index.md

Fixes a typo in an example in the docs for parse5-parser-stream.

parser-stream docs: parens required when destructuring parameter

---

packages/parse5-html-rewriting-stream/lib/index.js
packages/parse5-sax-parser/lib/index.js
packages/parse5-sax-parser/test/location-info.test.js

-  Fix `SAXParser` text end location (fixes #266).
- Move lazy emission logic from `RewritingStream::_handleToken` to `SAXParser::_handleToken`. This allows `SAXParser` to skip reshaping when no listeners are registered and simplifies interaction between two APIs.
- Make `SAXParser::pendingText` to keep a `CHARACTER` token instead of just chars. This aligns emission of pending text with other tokens and gives a single `_emitToken` point for `RewritingStream` to override (instead of additionally overriding `_emitPendingText` with similar logic).
- Remove `SAXParser::currentTokenLocation` state, instead just retrieving location from current raw or processed token. It was needed mainly to track location for consequent text tokens, but since `pendingText` is now a token, it can store its own …

Refactor emission logic of SAXParser and RewritingStream

---

packages/parse5-html-rewriting-stream/test/rewriting-stream.test.js
packages/parse5-sax-parser/lib/index.js
packages/parse5-sax-parser/test/sax-parser.test.js

The last chunk wasn't flushed when `.end()` on the stream is called without its own chunk, as in that case it doesn't invoke `_transform`.
Fixes #271.

SAX: Always flush the last chunk

---

bench/memory/sax-parser.js
bench/perf/index.js
packages/parse5-html-rewriting-stream/test/rewriting-stream.test.js
packages/parse5-parser-stream/lib/index.js
packages/parse5-parser-stream/test/parser-stream.test.js
packages/parse5-parser-stream/test/utils/parse-chunked.js
packages/parse5-plain-text-conversion-stream/test/plain-text-conversion-stream.test.js
packages/parse5-sax-parser/lib/index.js
packages/parse5-sax-parser/test/sax-parser.test.js
packages/parse5-serializer-stream/lib/index.js
packages/parse5-serializer-stream/test/serializer-stream.test.js
test/utils/common.js

Previously, all streams accepted buffer chunks, decoding each one individually into a string as UTF-8.
This is problematic due to several reasons:
1. It's not guaranteed that a binary stream is indeed UTF-8, and parse5 doesn't currently implement encoding detection to properly recognise anything else.
2. For any multibyte encoding, including UTF-8, it's not guaranteed that a binary chunk on its own is a valid text as a codepoint can be split between different chunks (this was not caught by tests because they already feed string chunks into the parser).
3. Writable parts of the stream didn't have `decodeString: false`, which means that by default Node.js would unnecessarily "decode" (d'oh, that naming is confusing) any string into a Buffer, feed it into a parser stream, and it would decode …

Accept only decoded string streams

---

packages/parse5/lib/serializer/index.js

I came across this issue in the test case ["Attribute in non-standard namespace"](https://github.com/web-platform-tests/wpt/blob/master/html/syntax/serializing-html-fragments/serializing.html#L118) while I was debugging jsdom.
This serializes them as `prefix:localName` - the [qualified name](https://dom.spec.whatwg.org/#concept-element-qualified-name) - rather than `namespace:localName`, according to the specification at https://html.spec.whatwg.org/multipage/parsing.html#attribute's-serialised-name.
This should probably include a test case, but it's not immediately clear to me how to test using an unknown namespace within the existing structure.

Fix serialization of attributes in non-standard namespaces

---

packages/parse5-htmlparser2-tree-adapter/lib/index.js
packages/parse5/docs/source-code-location/end-location.md
packages/parse5/docs/tree-adapter/interface.md
packages/parse5/lib/extensions/location-info/parser-mixin.js
packages/parse5/lib/tree-adapters/default.js
packages/parse5/test/location-info-parser.test.js

Hi,
I added the `updateNodeSourceCodeLocation` as discussed in #314 .
Code:
I decided to only pass the updated node location and not the whole location.
Tests:
I did not find test code specific to the default or htmlparser2 tree adapter.
All current tests (via npm run unit-tests) pass.
Documentation:
I added the function description to the tree adapter documentation and created a new end-location.md by copy&pasting the information from the other location documentation.

Add updateNodeSourceCodeLocation to the tree adapter

---

packages/parse5/lib/parser/index.js

as far as i can see, this is a typo.
it is currently causing failures in our linter (which depends on parse5) when parsing HR tags.
your tests are a little non-self-explanatory so if there's somewhere i can add one, please do let me know.

set hr tags as self closing

---

.github/dependabot.yml
.github/workflows/codeql-analysis.yml
.github/workflows/dependabot-automerge.yml
.github/workflows/nodejs-test.yml
.travis.yml

Also introduces Dependabot.
Travis.org is no longer supported, and the choice would have been to either switch to their .com offering, or switch CI providers entirely. GitHub Actions is the first party solution here, so let's use that!

chore(ci): Switch to GitHub Actions CI

---

packages/parse5/lib/parser/index.test.ts
packages/parse5/lib/parser/index.ts
packages/parse5/lib/tree-adapters/interface.ts

JSDOM currently monkey-patches parse5 to get these events. With this change, that is no longer necessary.
Fixes #237, #285.

feat(parser): Add hooks for stack events

---

packages/parse5-serializer-stream/lib/index.ts
packages/parse5/lib/index.ts
packages/parse5/lib/serializer/index.test.ts
packages/parse5/lib/serializer/index.ts
test/data/serialization/tests.json
test/utils/generate-serializer-tests.ts

Simplifies the serializer by removing the wrapping class, fixes mixed content (#333), adds the scripting flag (#332), and adds a `serializeOuter` method (#230, #378). Also fixes passing a `<template>` element to `serialize` resulting in an empty string.
The `parse5-serializer-stream` module should be deprecated after these changes.

Refactor & improve serializer

---

packages/parse5-parser-stream/lib/index.ts
packages/parse5/lib/index.ts
packages/parse5/lib/parser/index.test.ts
packages/parse5/lib/parser/index.ts
scripts/generate-parser-feedback-test/index.ts

The `_bootstrap` method leaves the parser in a broken-by-design state, which requires us to use non-null assertions to make TS happy. This PR removes this method, moving its arguments to the constructor.
This helps considerably with #377.

refactor(parser): Remove `_bootstrap` method

---

packages/parse5/lib/tokenizer/index.ts
packages/parse5/lib/tokenizer/preprocessor.ts
packages/parse5/lib/tokenizer/tokenizer-location-info.test.ts

Supersedes #397
Previously, `ctLoc` was overwritten on every new character. #397 attempted to improve this by maintaining the locations in an updated object, and creating copies when needed.
With this PR, we instead use explicit offsets when creating tokens. There is no more need to update locations; instead, we exploit the fact that a *DATA state is entered only after emitting the previous token.
This change should lead to a great reduction in allocations when using location information.

refactor(tokenizer): Use explicit offsets for locations

---

packages/parse5-sax-parser/lib/parser-feedback-simulator.ts
packages/parse5/lib/parser/index.ts
packages/parse5/lib/tokenizer/index.ts
scripts/generate-parser-feedback-test/index.ts

See #403 for details.
The parser currently first checks the insertion mode, and then the token type. By inverting this (checking first the token type, then the insertion mode), we prepare the parser to accept the events from #404.
This change also allowed foreign content checks to be greatly simplified.

refactor(parser): Invert event processing

---

packages/parse5/lib/tokenizer/index.ts
test/utils/generate-tokenization-tests.ts

Turns out a bug I _"fixed"_ in my fork (in https://github.com/inikulin/parse5/commit/70c1935552e90f23e2cbf4d0e2ce60d1da0b7e49) was actually the specced behaviour. This PR reintroduces the old behaviour.
Thanks to @untitaker for flagging this in https://github.com/html5lib/html5lib-tests/pull/144.

fix(tokenizer): No parse error on attribute quirk

---

packages/parse5/lib/parser/index.ts
packages/parse5/lib/parser/open-element-stack.test.ts
packages/parse5/lib/parser/open-element-stack.ts

Now that the tokenizer is using the delegate pattern, it only makes sense to update the `OpenElementStack` to follow the same pattern.

refactor: Use handler for `OpenElementStack`

---

packages/parse5-html-rewriting-stream/test/rewriting-stream.test.ts
packages/parse5-sax-parser/lib/index.ts
packages/parse5/lib/tokenizer/index.ts
packages/parse5/lib/tokenizer/preprocessor.ts

Fixes #292, #357
We would sometimes drop chunks before the corresponding tokens were processed by the rewriting stream. This led to #292. Now, we will drop buffers after emitting events.
BREAKING CHANGE: The SAX parser and rewriting stream will now emit text events when the underlying buffer will be dropped right after the event.
@qnighy I've adopted your test from #357 — hope that's okay! I'd also love it if you could make sure this works for you.

fix(tokenizer): Drop chunks after emitting tokens

---

packages/parse5-html-rewriting-stream/lib/index.ts
packages/parse5-html-rewriting-stream/test/rewriting-stream.test.ts
packages/parse5-sax-parser/lib/parser-feedback-simulator.ts
packages/parse5/lib/serializer/index.ts

Fixes #339
__Question:__ This allows users to _leak_ data from tags. Eg. inserting the text `</script> foo` would close the current script tag. There is no good solution that works for all special tags, and I'm not even sure this is an issue.
cc @nfriedly — I'd love to hear your take on this.

fix(rewriting-stream): Don't escape text in special tags

---

packages/parse5/lib/parser/parser-location-info.test.ts

Fixes #265
Turns out #265 has already been fixed. This adds a regression test for it.

test(parser): Add location test for script content

---

packages/parse5/lib/parser/index.ts
packages/parse5/lib/parser/parser-location-info.test.ts

Currently, we override the end locations for `html` and `body` tags on EOF. `body` will now take the end position from a closing `html` tag, if there was no closing `body` tag.
This isn't the most elegant solution, so happy for any suggestions of how to improve things.

fix(parser): Keep `html` and `body` end locations

---

packages/parse5-htmlparser2-tree-adapter/lib/index.ts
packages/parse5/lib/common/doctype.ts
packages/parse5/lib/serializer/index.ts
test/utils/generate-location-info-parser-tests.ts

I realised during the original refactor that `generateLocationInfoParserTests` didn't call some of the functions is was supposed to call. Digging into this now, it turned out that it was calling `escapeString` on the input before processing anything. That meant we would receive a single long string with all of the document's content, and only assert a single time that the received string matched the input.
Now, we properly walk the tree (depth first, from the deepest node), and test nodes along the way.
#436 was found during this effort.
Other changes necessary to make this work:
- `serializeOuter` was updated to serialise any kind of node.
- Removed `null` from document type functions (value was never used)
- **BREAKING:** Before, we would always add an empty `SYSTEM` identifier to the …

refactor: Make location info parser tests work

---

.github/workflows/pages.yml
package-lock.json
package.json
tsconfig.json

The bare minimum to generate docs with Typedoc, and update them on Github Actions. This is needed to have docs again, for eg. #422.
There are quite a few symbols that cannot be resolved right now. Part of the issue is https://github.com/TypeStrong/typedoc/issues/1835, which prevents symbols from being resolved across packages. We also have to expose additional symbols; eg. #301 will be a part of fixing that. All of that will be tackled after this PR.

docs: Introduce Typedoc

---

.eslintignore
.gitmodules
.prettierignore
package.json
packages/parse5/lib/tokenizer/index.test.ts
test/utils/generate-parsing-tests.ts

And use them for the tokenizer, benchmarks & to generate feedback tests.
https://github.com/html5lib/html5lib-tests/pull/144 got merged, which allows us to adopt the upstream tests.

test: Add upstream html5lib-tests

---

packages/parse5/lib/parser/index.test.ts
packages/parse5/lib/parser/index.ts

The behaviour for parsing foreign content was updated in https://github.com/whatwg/html/pull/6455, https://github.com/whatwg/html/pull/6399, and https://github.com/whatwg/html/pull/6736. This catches us up to the current specced behaviour.

feat(parser): Align foreign content with spec

---

packages/parse5/package.json

The `generate-parser-feedback-test` script currently fails due to deep imports from `parse5` not being allowed. I assume this will apply to all submodules that currently have deep imports.
For now, let's allow deep imports of all files within `parse5`.

fix(package): Allow deep imports from `parse5`

---

packages/parse5-parser-stream/lib/index.ts
packages/parse5-sax-parser/lib/index.ts
packages/parse5/lib/parser/index.ts
packages/parse5/lib/tokenizer/index.ts
packages/parse5/lib/tokenizer/tokenizer-location-info.test.ts
test/utils/generate-tokenization-tests.ts

Removes the `getNextToken` function of the tokenizer, as well as all parsing loops. `getNextToken` was already a bit of a misnomer, as it would emit tokens to token handlers instead of returning it to the caller. Turns out parsing loops aren't necessary anymore, so let's get rid of them.
Script handling had to be updated slightly to support this. Now, a script handler is supplied to the parser constructor, and will be called whenever a script is encountered. This simplifies script handling logic in a few places.

refactor: Remove `getNextToken` method

---

.eslintignore
package.json
tsconfig.json

`typedoc` builds successfully on my local ARM Mac, but runs out of memory on GitHub Actions. I suspect that the limit needs to be bumped slightly to make things go for now.
This is a known issue: https://github.com/TypeStrong/typedoc/issues/1606
This PR also includes a config change of typedoc to stop emitting source code, and to exclude functions marked as `@internal`. Plus, ESLint will now ignore built docs.

chore(docs): Increase Node memory limit for docs

---

package-lock.json
packages/parse5-htmlparser2-tree-adapter/lib/index.ts
packages/parse5-htmlparser2-tree-adapter/package.json

The new version includes fixed location types. Removed all casts that were necessary to make this work before.

fix(htmlparser2-adapter): Use domhandler@4.3.1

---

.gitattributes

This will make GitHub's language statistics ignore all test files.

chore: Fix .gitattributes

---

.github/FUNDING.yml
SECURITY.md

I am now lifting the project on Tidelift. That means we can now rely on Tidelift to help with security issues.

chore: Setup Tidelift, add SECURITY.md

---

packages/parse5-htmlparser2-tree-adapter/lib/index.ts
packages/parse5-parser-stream/test/utils/parse-chunked.ts
packages/parse5/lib/parser/index.test.ts
packages/parse5/lib/parser/index.ts
packages/parse5/lib/serializer/index.test.ts
packages/parse5/lib/serializer/index.ts
packages/parse5/lib/tree-adapters/default.ts
scripts/generate-parser-feedback-test/index.ts
test/utils/common.ts

@43081j already had this in his TS conversion. Makes us use objects for the adapters, which allows TS to properly type check them. This means we will have to type the default options as `{Parser,Serializer}Options<any>`; please let me know if you can think of an alternative approach to make this type safe.

refactor: Use objects for adapters

---

package-lock.json
packages/parse5-html-rewriting-stream/lib/index.ts
packages/parse5-html-rewriting-stream/package.json
packages/parse5/lib/serializer/index.ts
packages/parse5/lib/tokenizer/index.ts
packages/parse5/package.json

`entities` is now an ES Module, which should make ES Module fans happy. (No more CJS dependencies!)
The new version features a smaller decode tree, which required an update to the tokenizer. It also includes `escapeText` and `escapeAttribute` functions that implement the required behavior for the HTML serializer; I replaced parse5's `escapeString` function with these.

Bump `entities` to `4.1.1`, update code

---

packages/parse5-parser-stream/lib/index.ts
packages/parse5-parser-stream/test/location-info.test.ts
packages/parse5-parser-stream/test/parser-stream.test.ts
packages/parse5-parser-stream/test/scripting.test.ts
packages/parse5-parser-stream/test/utils/parse-chunked.ts
packages/parse5/lib/index.ts
packages/parse5/lib/parser/index.test.ts
packages/parse5/lib/parser/index.ts
test/utils/generate-parsing-tests.ts

feat(parser-stream): Support parsing fragments

---

package.json
packages/parse5-htmlparser2-tree-adapter/package.json
packages/parse5/package.json
packages/parse5/tsconfig.cjs.json

And refactor how CJS is being built.

feat(htmlparser2-adapter): Add CJS build

---

packages/parse5-html-rewriting-stream/package.json
packages/parse5-htmlparser2-tree-adapter/package.json
packages/parse5-parser-stream/package.json
packages/parse5-plain-text-conversion-stream/package.json
packages/parse5-sax-parser/package.json
packages/parse5/package.json

The root `tsconfig.json` file asks for source maps to be generated. If we ship these with the published packages, they will point at the `.ts` files in the relative directory, which aren't shipped with the packages. This makes the source maps useless for debugging, and a source of errors otherwise.
I originally wanted to adopt the approach from `entities`, where I used the `sourceRoot` field to point to the original source files on GitHub (https://github.com/fb55/entities/pull/788). Unfortunately, this doesn't work with `tsc --build` (https://github.com/microsoft/TypeScript/issues/25613) and would require a work-around[^1].
[^1]:  Something along the lines of defining a source root in each package's `tsconfig.json`, then updating all of them to point to a specific commit in a `sed` …

fix(package): Don't publish source maps

---

packages/parse5/lib/index.ts

Page: https://parse5.js.org/modules/parse5.html#parseFragment
Variable `parser` should be `parse5`. As it's declared in beginning of the code example `const parse5 = require('parse5');`, `parser` variable would be undefined.

docs: Fix small typo in code example

---

.github/workflows/nodejs-test.yml
.gitignore

chore(ci): Add coverage reporting

---

.gitignore
README.md
package.json
packages/parse5-html-rewriting-stream/test/rewriting-stream.test.ts
packages/parse5-htmlparser2-tree-adapter/lib/index.ts
packages/parse5-parser-stream/test/utils/parse-chunked.ts
packages/parse5-sax-parser/test/sax-parser.test.ts
packages/parse5/lib/parser/formatting-element-list.test.ts
packages/parse5/lib/parser/formatting-element-list.ts
packages/parse5/lib/parser/open-element-stack.test.ts
packages/parse5/lib/tokenizer/index.test.ts
packages/parse5/lib/tokenizer/index.ts

Removes all low-hanging fruit for #515

refactor: Improve code coverage

---

package-lock.json
packages/parse5-htmlparser2-tree-adapter/lib/index.ts
packages/parse5-htmlparser2-tree-adapter/package.json

domhandler now allows `Document` nodes as children. This allows us to remove a cast from the relevant adapter.

chore(deps): Bump domhandler, remove cast

---

packages/parse5/lib/parser/index.ts

Fixes #533
A PR with a test was opened at https://github.com/html5lib/html5lib-tests/pull/146

fix(parser): Have `</button>` close `<p>`

---

packages/parse5-parser-stream/test/parser-stream.test.ts
packages/parse5/lib/parser/index.test.ts
packages/parse5/lib/parser/index.ts
packages/parse5/lib/serializer/index.test.ts
packages/parse5/lib/tokenizer/index.test.ts
packages/parse5/lib/tokenizer/index.ts
test/utils/generate-parsing-tests.ts

This is a bundle of several small changes that came up with https://github.com/html5lib/html5lib-tests/pull/147
Overview over the changes:
- `reconsumeInState` will now call the state directly, instead of retreating.
- We knew in several places that we wanted to get to the template end logic of the _in head_ insertion mode. By factoring out that insertion mode, we can skip some steps.
- Added a test for serialising unknown nodes (which should lead to an empty string)
- Test indices were previously global, which resulted in ignores failing after an unrelated test was added. Now, test indices are local.
- Simplify a conditional statement to a ternary (following the [Principle of Most Restrictive Production](https://blog.izs.me/2022/04/principle-of-most-restrictive-production/))

refactor: Several small changes

---

packages/parse5/lib/parser/formatting-element-list.ts
packages/parse5/lib/parser/open-element-stack.ts
packages/parse5/lib/serializer/index.ts
tsconfig.json

Also explicitly sets `moduleResolution`. This reported some missing file extensions for type imports, which were added.
Fixes #556

refactor(tsconfig): Set `module` to `Node16`

---

packages/parse5/lib/tree-adapters/default.ts

This was initially to change `NodeType` into a union, but that doesn't make sense since we wouldn't make use of the type then, we'd just use the string literal types anyway.
Nothing references `NodeType` outside the tree adapter and it isn't exported publicly (`index.ts`) currently.
So instead i just dropped `NodeType` and used a string literal type for each node type.
@fb55 what do you think? this matches how it was originally (pre-rewrite) and allows people to create nodes without pulling the (currently not exported afaict) enum in.
if anyone wants the type union, they can do `Node['nodeName']`, which we could alias into `NodeType` if its still of any use

feat(parse5): use string types for node names

---

package-lock.json
packages/parse5/package.json

This version is already on npm — forgot that I should PR the release first.
Once this is merged, I'll create a tag and publish release notes.
My gut feeling is that, going forward we should skip versions for the other packages, so that versions numbers across packages are monotonically increasing. (Ie. `parse5-rewriter-stream@7.8.9` is guaranteed to be published after `parse5@7.6.5`.)

Bump parse5 to 7.1.0

---

package-lock.json
packages/parse5-htmlparser2-tree-adapter/package.json
packages/parse5/package.json

The `package.json` that's added for CJS was not added when we switched to a whitelist in #516.
Fixes #663

fix(package): Fix CJS bundle, bump to parse5@7.1.1

---

.github/workflows/codeql-analysis.yml
.github/workflows/nodejs-test.yml
.github/workflows/pages.yml

Dependabot will now update them as new versions are released.
This is done to improve parse5's score in the OpenSSF scorecard, visible here: https://deps.dev/npm/parse5

chore(ci): Pin GitHub Action dependency versions

---

packages/parse5/lib/index.ts

export error codes
fix #555
https://github.com/inikulin/parse5/pull/418#discussion_r997476069
<blockquote>
this breaks [rehype/test/parse-error.js](https://github.com/rehypejs/rehype/blob/620bb9cdf53a4dbe70adfca8d66c8824eb3f513f/test/parse-error.js#L7) in https://github.com/rehypejs/rehype/pull/113
```js
import p5errors from 'parse5/lib/common/error-codes.js'
```
> ```Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/common/error-codes.js' is not defined by "exports" in node_modules/parse5/package.json imported from test/parse-error.js```
wontfix in rehype, as [ERR](https://github.com/inikulin/parse5/blob/075be2e712644410e1ceae67ebabad958bc0b66e/packages/parse5/lib/common/error-codes.ts#L9) is not exported by parse5
&rarr; export as ErrorCodes?
https://nodejs.org/api/esm.html …

fix: export ERR as ErrorCodes from error-codes.js

---

packages/parse5/lib/parser/index.test.ts
packages/parse5/lib/tokenizer/index.test.ts
packages/parse5/lib/tokenizer/preprocessor.ts

Peeking didn't properly support carriage returns, which led the parser to hang in special tags.
Fixes #710

fix(tokenizer): Properly handle CR when peeking

---

packages/parse5-parser-stream/package.json

I want to use the parser stream in Cheerio, and am blocked by the current ESM nature of the module. The path of least resistance is to add a CJS build for the parser stream.

feat(parser-stream): Add CJS build

---

packages/parse5-parser-stream/package.json
packages/parse5/package.json

This release includes `parse5` and `parse5-parser-stream`.
Changelog:
* Export `ERR` as `ErrorCodes` by @milahu in https://github.com/inikulin/parse5/pull/704
* Properly handle CR when peeking by @fb55 in https://github.com/inikulin/parse5/pull/715
* Add CJS build of `parser-stream` by @fb55 in https://github.com/inikulin/parse5/pull/716
**Full Changelog**: https://github.com/inikulin/parse5/compare/v7.1.0...v7.1.2

Bump version to v7.1.2

---

README.md

Adresses badges/shields#8671
Also updates a few remaining `http://` links to use `https://`

docs(readme): Fix CI badge

---

packages/parse5/lib/serializer/index.ts

This code sample is using the wrong variable name. The declared variable is `html`, but on line 104 it tries to log a variable called `str`.
In line with [the similar example in the same file](https://github.com/inikulin/parse5/blob/badd96506b99a4101fc71853720d689ca573d592/packages/parse5/lib/serializer/index.ts#L69-L72), I renamed the variable to `str`.

docs: fix variable name in sample code

---

package.json
packages/parse5-html-rewriting-stream/typedoc.json
packages/parse5-htmlparser2-tree-adapter/typedoc.json
packages/parse5-parser-stream/typedoc.json
packages/parse5-plain-text-conversion-stream/typedoc.json
packages/parse5-sax-parser/lib/index.ts
packages/parse5-sax-parser/typedoc.json
packages/parse5/lib/index.ts
packages/parse5/lib/parser/index.ts
packages/parse5/lib/tree-adapters/interface.ts
packages/parse5/typedoc.json
tsconfig.json
typedoc.base.json

typedoc has recently changed the way it builds monorepos, which led to website deploys failing. The changes remove the need to increase Node's heap size, but add several config files that have to be added.
I've also tried to remove a lot of the warnings that typedoc produces, by added `@internal` and `@private` comments where appropriate.
Fixes #874, by adding an export for all of the relevant types.

chore(site): Fix typedoc config

---

packages/parse5/lib/parser/index.ts
packages/parse5/lib/tokenizer/index.ts

Some projects in the wild depend on extending `Parser` and `Tokenizer` by overriding certain methods and using internals we don't publish on our public API.
This just moves all the private members to be protected so those projects can upgrade to 7.x.
Not everything should be protected but it seems our current class members all fit the criteria.
Fixes #992 
i think this should be fine but let me know your thoughts @fb55

feat(parse5): change parser/tokenizer methods to be protected

---

packages/parse5-htmlparser2-tree-adapter/lib/index.ts
packages/parse5/lib/tree-adapters/default.ts
packages/parse5/lib/tree-adapters/interface.ts

This PR exposes the `createTextNode()` method on the default tree adapter (#1031).
I pulled down the tests from [`html5lib-tests`](https://github.com/html5lib/html5lib-tests/tree/master) and ran them locally but wasn't sure there's any additional unit testing that should be included as part of this change.
I'm planning to open a follow-up PR on [parse5-tools](https://github.com/parse5/parse5-tools) to replace the existing `createTextNode` with the one provided here as described in #1031.

refactor: expose createTextNode on defaultTreeAdapter

---

.github/workflows/nodejs-test.yml

Several dependency updates are stalled as they no longer support old Node versions, so let's drop them from CI.

chore(ci): Update tested NodeJS versions

---

packages/parse5/lib/common/html.ts
packages/parse5/lib/parser/index.ts
packages/parse5/lib/parser/open-element-stack.ts

Replaces the array searches and map lookups with sets and switch statements.
Also replaces the `isNumberedHeader` helper function with a set.

refactor(open-element-stack): Use sets everywhere

---

package-lock.json
tsconfig.json

we needed `skipLibCheck` because `@types/node` has errors under latest typescript for whatever reason
that's why dependabot couldn't figure it out

chore: upgrade to typescript 5.6

---

packages/parse5/lib/parser/index.test.ts
packages/parse5/lib/parser/index.ts

Fixes #972
This also adds a test to make sure that "raw text" tags (e.g. `<noembed>`, `<noframes>`, `<style>`, etc.) all work the same. For the test, I'm reusing the same repro from #972.
Before this fix, all the tests pass except for `<noframes>` specifically.

fix: fix `<noframes>` parsing

---

tsconfig.json
typedoc.json

Each of our `tsconfig.json` inherits the root `tsconfig.json`. This root config currently contains the typedoc configuration too, including `endPointStrategy: "packages"`.
This leads to each package in the repo having its own root-level typedoc config, which is causing typedoc to fail right now.
By moving the config to a `typedoc.json` at the root, we can continue inheriting `tsconfig.json` without accidentally inheriting the typedoc config.

fix: use typedoc config to avoid accidental inheritance

---

package-lock.json
packages/parse5-htmlparser2-tree-adapter/package.json
packages/parse5/package.json

Release includes parse5 and parse5-htmlparser2-tree-adapter.
cc @fb55 I'm then going to merge this, tag main as 7.2.0 and npm publish the two individual packages 👀

chore: bump version to 7.2.0

---

packages/parse5/lib/index.ts
packages/parse5/lib/parser/open-element-stack.test.ts

Exports the tree adapter types as a namespace, individually. This reintroduces typescript 4.x support, which we accidentally broke in a non-breaking release.
Fixes #1299 
Before we merge this I need to double check it really does fix the problem. I tried building it with 4.x and it works but I need to check the types are still the same

fix: export tree adapter types as namespace to support TS4.x

---

eslint.config.js
packages/parse5-html-rewriting-stream/lib/index.ts
packages/parse5-parser-stream/lib/index.ts
packages/parse5-sax-parser/lib/index.ts
packages/parse5/lib/parser/parser-location-info.test.ts
packages/parse5/lib/serializer/index.test.ts
packages/parse5/lib/tokenizer/index.test.ts

Removes our override such that `any` is no longer allowed, and replaces usages of it.
@fb55 this uncovered a curiosity:
the `Updating node source code location (GH-314)` test was basically asserting that you can have a custom source code location setter. i.e. you can have your own location shape
however, we have a strong type for `Location` and all tree adapters are required to return an `ElementLocation` from `getSourceCodeLocation` (which itself is a `Location`).
so while we do let you set whatever you want in `setSourceCodeLocation`, it doesn't make much sense to set anything that isn't a `Location`, as you need to get that back out in `getSourceCodeLocation` anyway.
tldr i think the test and the use case made sense way back, but has lost its meaning as we've strengthened types

chore: enable no-explicit-any rule as error level

---

.c8rc.json
.github/workflows/nodejs-test.yml
.mocharc.json
bench/memory/sax-parser.js
bench/perf/index.js
eslint.config.js
package-lock.json
package.json
packages/parse5-html-rewriting-stream/test/rewriting-stream.test.ts
packages/parse5-parser-stream/test/location-info.test.ts
packages/parse5-parser-stream/test/parser-stream.test.ts
packages/parse5-parser-stream/test/scripting.test.ts
packages/parse5-plain-text-conversion-stream/test/plain-text-conversion-stream.test.ts
packages/parse5-sax-parser/test/location-info.test.ts
packages/parse5-sax-parser/test/sax-parser.test.ts
packages/parse5/lib/parser/formatting-element-list.test.ts
packages/parse5/lib/parser/index.test.ts
packages/parse5/lib/parser/open-element-stack.test.ts
packages/parse5/lib/parser/parser-location-info.test.ts
packages/parse5/lib/serializer/index.test.ts
packages/parse5/lib/tokenizer/index.test.ts
packages/parse5/lib/tokenizer/tokenizer-location-info.test.ts
test/utils/common.ts
test/utils/generate-location-info-parser-tests.ts
test/utils/generate-parsing-tests.ts
test/utils/generate-serializer-tests.ts
test/utils/generate-tokenization-tests.ts
vitest.config.js

I'd like to figure out how to use `include` to select coverage rather than having to individually `exclude` everything before merging. but it isn't a blocker
possible alternative to #1268 
vitest seems to produce better coverage somehow. i couldn't figure out why mocha/c8 was falling over

chore: migrate to vitest

---

packages/parse5-html-rewriting-stream/README.md
packages/parse5-htmlparser2-tree-adapter/README.md
packages/parse5-parser-stream/README.md
packages/parse5-plain-text-conversion-stream/README.md
packages/parse5-sax-parser/README.md

Used '_' where it should have been '-'

Fix broken links to documentation

---

packages/parse5/lib/parser/index.ts
packages/parse5/lib/parser/open-element-stack.ts

Changes the element stack such that the current element and ID can be
`undefined`, as this is already true but not represented in the types.
Also then updates any usages to account for this.
Depends on #1435 - it is basically that PR but with all other usages and the types fixed

fix: account for undefined in element stack

---

package-lock.json
packages/parse5-html-rewriting-stream/package.json
packages/parse5/package.json

Bumps parse5 to 7.3.0, and parse5-html-rewriting-stream to 7.1.0

chore: bump to version 7.3.0

---

package.json
packages/parse5-html-rewriting-stream/package.json
packages/parse5-htmlparser2-tree-adapter/package.json
packages/parse5-parser-stream/package.json
packages/parse5-plain-text-conversion-stream/package.json
packages/parse5-sax-parser/package.json
packages/parse5/package.json

Switches the 3 remaining dual packages to ESM only:
- `parse5-htmlparser2-tree-adapter`
- `parse5-parser-stream`
- `parse5`
**NOTE:** we still haven't decided if we are ready to do this yet. just leaving this draft here for when we do one day

feat: switch to ESM-only

---

package-lock.json
packages/parse5-html-rewriting-stream/package.json
packages/parse5-htmlparser2-tree-adapter/package.json
packages/parse5-parser-stream/package.json
packages/parse5-plain-text-conversion-stream/package.json
packages/parse5-sax-parser/package.json
packages/parse5/package.json

Bumps all packages and their parse5 dependencies to 8.0.0.
This isn't strictly necessary as some packages will continue to work
with 7.x, but it may be easier for maintenance in future to draw the
line.

feat: bump to 8.0.0
